fixing Python 3.6 import problem
By running command `python -m gitautodeploy --config config.json` on python 3.6.8 I have received error:

```
git-auto-deploy/gitautodeploy/cli/config.py", line 355, in init_config
    from ..models import Project
ValueError: attempted relative import beyond top-level package
```
which is easily fixed (with backwards compatibility) with a try/except clause. Point is that python 3 changes relative includes which also means we need to be package dependent.